### ISSUE TITLE
Issue when bulding rosconsole

### ISSUE THREAD

**Issue by Marcus-Davi** [ros-noetic-arch/ros-noetic-xmlrpcpp#2]
Whenever I try to download and build, either using **yay -S ros-noetic-ros-base** or using **makepkg** within ros-noetic-rosconsole, the following happens.

```
==> Starting build()...
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/marcus/.cache/yay/ros-noetic-xmlrpcpp/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python (found suitable version "3.8.5", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Found PY_em: /usr/lib/python3.8/site-packages/em.py
-- Using empy: /usr/lib/python3.8/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /home/marcus/.cache/yay/ros-noetic-xmlrpcpp/src/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Found gmock sources under '/usr/src/gmock': gmock will be built
CMake Warning at /usr/src/gmock/CMakeLists.txt:43 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.


CMake Warning at /usr/src/googletest/CMakeLists.txt:54 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.


-- Found PythonInterp: /usr/bin/python (found version "3.8.5")
-- Found Threads: TRUE
-- Using Python nosetests: /usr/bin/nosetests-3.8
-- catkin 0.8.8
-- BUILD_SHARED_LIBS is on
-- Found Boost: /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: thread
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marcus/.cache/yay/ros-noetic-xmlrpcpp/src/build
Scanning dependencies of target xmlrpcpp
[  8%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcClient.cpp.o
[ 16%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcDispatch.cpp.o
[ 25%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcServer.cpp.o
[ 33%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcServerConnection.cpp.o
[ 41%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcServerMethod.cpp.o
[ 50%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcSocket.cpp.o
[ 58%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcSource.cpp.o
[ 66%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcUtil.cpp.o
[ 75%] Building CXX object CMakeFiles/xmlrpcpp.dir/src/XmlRpcValue.cpp.o
[ 83%] Building C object CMakeFiles/xmlrpcpp.dir/libb64/src/cdecode.c.o
[ 91%] Building C object CMakeFiles/xmlrpcpp.dir/libb64/src/cencode.c.o
make[2]: *** No rule to make target '/usr/lib/libconsole_bridge.so.0.4', needed by 'devel/lib/libxmlrpcpp.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/xmlrpcpp.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

This happens with ros-noetic-desktop and ros-noetic-desktop-full as well.

**Comment by acxz** [comment]
@Marcus-Davi were you able to resolve your issue, with a `yay -Syu ros-noetic-desktop-full --rebuildtree`? If not please let me know. Sorry for moving these issues around so much, I mistook which package was causing the error. Its important we keep the errors associated with which packages we get them with, so that others will have an easier time finding them. Also do you mind if I delete your duplicate issue?

**Comment by Marcus-Davi** [comment]
Sure ! you may delete the duplicate, I'm sorry about that.

Unfortunately, the error persists, no matter the repository I use (base, desktop or full). I've also tried the following: 

- Remove ~/.cache/yay/ for a totally clean build;
- Remove all "ros-noetic-*" packages before installing
- Using either **yay -S ros-noetic-ros-base --rebuildtree**, **yay -S ros-noetic-desktop --rebuildtree** or **yay -S ros-noetic-desktop-full --rebuildtree**, always using [A] option to select clean build. I guess it doesn't matter at the end, since the issue is related to the 'xmlrpcpp' package, but I tried anyway.

It keeps pointing to a library that I don't have (libconsole_bridge.so.0.4). Maybe there is some way to consistently point the dependency to "libconsole_bridge.so" or "libconsole_bridge.so.1.0" during build? I don't understand much of version dependency in arch packages, but that would fix the problem for me !

**Comment by Marcus-Davi** [comment]
Sure ! you may delete the duplicate, I'm sorry about that.

Unfortunately, the error persists, no matter the repository I use (base, desktop or full). I've also tried the following:

 

- Removing ~/.cache/yay/ for a totally clean build;

 

- Removing all "ros-noetic-*" packages before installing

 

- Using either "yay -Syu ros-noetic-ros-base --rebuildtree", "yay -Syu ros-noetic-desktop --rebuildtree" or "yay -Syu ros-noetic-desktop-full --rebuildtree", trying both [A] and [N] options when cleaning. I guess it doesn't matter at the end, since the issue is related to the 'xmlrpcpp' package, but I tried anyway.

It keeps pointing to a library that I don't have (libconsole_bridge.so.0.4). Maybe there is some way to consistently point the dependency to "libconsole_bridge.so" or "libconsole_bridge.so.1.0" during build? I don't understand much of version dependency in arch packages, but that would fix the problem for me !

**Comment by acxz** [comment]
Can you remove `~/.cache/yay` and try `yay -Syu ros-noetic-xmlrpcpp --rebuildtree` with `A`?
Let's focus on the package which is causing the error and not worry about `ros-noetic-desktop/desktop-full`.

Oh also one more thing, what OS are you using?

**Comment by Marcus-Davi** [comment]
Output of archey3 of my system.
```
OS : Arch Linux x86_64
Hostname : laptop-lenovo
Kernel Release : 5.7.12-arch1-1
WM : i3
DE : None
Packages : 613
RAM : 1452 / 7883 MB
Processor : Intel Core I7-4700MQ CPU @ 2.40 GHz
```

I've removed all ros-noetic-* packages and tried the suggested steps. Still the same problem !

**Comment by acxz** [comment]
Please do not use images @Marcus-Davi, when searching through a webpage or with github' search feature, we cannot search inside of an image.

hmm okay let's take this step by step.
Can you show the output of `ls ~/.cache/yay`?
And then can you `rm -rf ~/.cache/yay`?
And then can you show the output of `ls ~/.cache/yay`?

**Comment by Marcus-Davi** [comment]
OK ! Here it goes : 
```
marcus@laptop-lenovo:~ ls ~/.cache/yay/
completion.cache  ros-noetic-xmlrpcpp
marcus@laptop-lenovo:~ rm -rf ~/.cache/yay/
marcus@laptop-lenovo:~ ls ~/.cache/yay/
ls: cannot access '/home/marcus/.cache/yay/': No such file or directory
```

**Comment by acxz** [comment]
sweet okay now let's run `yay -Syu ros-noetic-cpp-common`
and then `yay -Syu ros-noetic-rostime`
after that can you show the output of `ls ~/.cache/yay`?

**Comment by Marcus-Davi** [comment]
All right, it install both packages directly and successfully. It leaves no MAKEPKG folders in .cache/yay
Output of `ls ~/.cache.yay` :
```
marcus@laptop-lenovo:~ ls .cache/yay/
completion.cache
```

**Comment by acxz** [comment]
I assume you are using arch4edu then?

**Comment by Marcus-Davi** [comment]
Correct

**Comment by acxz** [comment]
Okay so that might have to do with the issue. Let's make sure. Can you run `yay -Syu ros-noetic-xmlrpcpp`? and show the output of `ls ~/.cache/yay` again?

If you still get the error, can you remove the arch4edu repos and associated packages and try again with `yay -Syu ros-noetic-xmlrpcpp --rebuildtree`.

It could be that the arch4edu build hasn't been rebuilt yet. But they are usually on top of that, let's see what happens.

**Comment by Marcus-Davi** [comment]
After running `yay -Syu ros-noetic-xmlrpcpp`, it gave me the same old error. Then, 
```
marcus@laptop-lenovo:~ ls ~/.cache/yay/
completion.cache  ros-noetic-xmlrpcpp
```

Afterwards I removed arch4edu and right away got a few options on which packaged to use for the build (It didin't happen when using arch4edu)

It installed successfully! I guess it first tries to grab an outdated package from arch4edu but have mismatched versions with your github repository. I wonder, if there are packages with the same name in arch4edu and AUR, it prioritizes arch4edu ?

**Comment by acxz** [comment]
> I wonder, if there are packages with the same name in arch4edu and AUR, it prioritizes arch4edu ?

I believe that is what happens.

Yeah hosting all the ros packages in arch4edu is still a work in progress. Sorry you had to go through this trouble. But I'm glad it works now!

**Comment by Marcus-Davi** [comment]
I didn't mind at all! 

In fact, I really appreciate your work. If I can help with anything, I'd be happy to.

**Comment by acxz** [comment]
Thanks for your complements!

Right now most of the noetic packages are stable, but we do need to create binary packages through arch4edu. Take a look at this issue: https://github.com/arch4edu/arch4edu/issues/78
and see if you can help out there, that would really mean a lot to the community.

Feel free to ask more on that issue thread, petronny is a standup guy.
See the following wiki page on how to help out. In essence creating the `lilac.py` file and making a PR to the repo. https://github.com/arch4edu/arch4edu/wiki/Add-a-package-to-arch4edu
You can also look at the existing ros packages in that repo and base new PRs from those.

It is also a good learning opportunity/stepping stone.
