### ISSUE TITLE
Package no longer builds

### ISSUE THREAD

**Issue by alexdewar** [ros-noetic-arch/ros-noetic-xmlrpcpp#3]
I'm getting the following error

```
make[2]: *** No rule to make target '/usr/lib/libconsole_bridge.so.0.4', needed by 'devel/lib/libxmlrpcpp.so'. Stop.
```

**Comment by acxz** [comment]
Seems like a dup of #2 

Can you try the suggestions there? Specically this comment: https://github.com/ros-noetic-arch/ros-noetic-xmlrpcpp/issues/2#issuecomment-670725481 involving removing arch4edu and doing a clean rebuild

gonna close this issue if you have further questions/comments please post at #2.

**Comment by alexdewar** [comment]
Ah yes, that did the trick. Thanks for the help!
